### PR TITLE
New task for Sass

### PR DESCRIPTION
**Pull request by pstuart2**
I love the extendability of Phing. Currently switching to it from Ant but needed a couple extra tasks. Here is one I wrote for Sass (http://sass-lang.com/).  Plan on a similar for the YUICompressor.

### CODE REVIEW

**Comment by anroots** [comment]
I'm disheartened to discover Phing lacks a task for this.

**Comment by mrook** [comment]
@anroots @pstuart2 @JostBaron sorry for not paying closer attention to this PR and #206. Could you work together to come up with a PR for a sass task, which can potentially serve both use cases (phpsass library and sass installed as a gem)

I'm not sure what the status of phpsass is (the website seems broken), so that may or may not influence the implementation.

**Comment by anroots** [comment]
phpsass seems discontinued @ github. http://leafo.net/scssphp/ is an alternative.

Using the gem assumes the build system has Ruby and the gem installed. This is often not possible (building with Phing on a Bamboo / Jenkins agent whose capabilities do not include Ruby), hence my search for a Composer-downloadable, PHP based approach.

I managed to solve my problem by using Phing's ExecTask and getting the build agent to support Ruby+gem.

**Comment by kenguest** [comment]
Is there any progress on this? Looking at #206 and #151 I would like to see these getting a fresh look - for my own purposes in work I can just <exec> against the gem installed sass tool but would prefer to see  a more mature and less error prone solution.

**Comment by mrook** [comment]
@kenguest I haven't received replies from the original submitter(s) yet. If you're interested in pushing this further I'm all ears, I unfortunately don't have the time right now.

**Comment by kenguest** [comment]
@mrook ok. Thanks for your quick response - I'll see if those PRs can be merged together under a new separate one and if any other tweaks can be made for a combined sass task.

**Comment by kenguest** [comment]
@mrook My initial attempt at merging the two PRs together is at https://github.com/kenguest/Phing-Sass/  - once I get it up to standard I'll make a pull request of my own.

Using @anroots suggestion my version uses Leafo's scssphp library and have left @pstuart2 credited in the source considering the bulk of the work is still his :-)

**Comment by mrook** [comment]
Excellent! Let me know if you need assistance :)

**Comment by mrook** [comment]
I'm closing this one in favor of the work being done in #502.

**Pull request closed without merging**
