### PR TITLE
SCA with Php Inspections (EA Extended)

### PR DESCRIPTION
**Pull request by kalessil**
Performance tweaks and minor simplifications.

PS: `$xml = simplexml_load_string(file_get_contents($filePath));` is a bug-fix for https://bugs.php.net/bug.php?id=62577

### CODE REVIEW

**Comment by kalessil** [comment]
Seems 0413f7b break build, will revert it later.

**Comment by kenguest** [comment]
Using get_class() with no parameters would break against/with PHP7.2 anyway...

There's a maxim of "if it ain't broke, don't fix it." - something to consider! :-)

**Comment by kalessil** [comment]
Closing, re-created the PR in #770

**Comment by kalessil** [comment]
@kenguest, this perfectly applies to legacy code bases =) 
I think it worth contributing something back to this great project =)

**Pull request closed without merging**
