### PR TITLE
Support Symfony 4.0

### PR DESCRIPTION
**Pull request by pgodel**
This PR adds support for Symfony 4.0 components to composer.json 

#SymfonyConHackday2017

### CODE REVIEW

**Comment by VasekPurchart** [comment]
@mrook could you please make a release with this change? Otherwise this blocks anyone using Phing from updating Symfony.

**Comment by mrook** [comment]
@VasekPurchart I'll try to get that out soon. Hopefully before the end of the year, but I can't guarantee that.

**Comment by VasekPurchart** [comment]
@mrook ok, thanks for the info :)

**Comment by mrook** [comment]
@VasekPurchart 2.16.1 was just released.

**Pull request merged**
