### PR TITLE
Implement solution for ticket 1222

### PR DESCRIPTION
**Pull request by llaville**
Take care that depending of your choice, some code may be reduced if you consider to refactor base class BatchTest and changed private properties and methods to protected

### CODE REVIEW

**Comment by mrook** [comment]
Thanks for the PR, but Phing needs to remain compatible with at least 5.3 (and preferably 5.2 as long as we can get away with it). "yield" is 5.5+

**Comment by llaville** [comment]
@mrook Yes, I understand, but if you look deep inside, you 'll see that only platform with PHP 5.5+ will used the generator feature. PHP 5.2, 5.3, 5.4 will still use default behavior.

**Comment by llaville** [comment]
@mrook Did you have time to deepthly explored my solution and see that it is backward compatible with all versions, especially lower 5.4, 5.3, 5.2

**Comment by mrook** [comment]
No, I'll try to take a look at it soon. Some tests are failing though.

**Comment by llaville** [comment]
ping @mrook any news since 2 months ?

**Comment by mrook** [comment]
Can you rebase the PR and see if the failing tests can be fixed?

**Pull request closed without merging**
