### PR TITLE
Abstracting FileParser to use factory class, adding yaml config support.

### PR DESCRIPTION
**Pull request by grasmash**
Rebasing and resubmitting work initially done in https://github.com/phingofficial/phing/pull/263/

### CODE REVIEW

**Comment by grasmash** [comment]
Hm. I'm not sure what's failing about the PHP 5.2 build?

**Comment by grasmash** [comment]
Oddly, installing PEAR packages is failing. I don't believe that this pull request affects any PEAR packages. @mrook Any idea what might be going on?

**Comment by grasmash** [comment]
I've removed the changes to automated tests to verify that is not the issue causing the failure.

**Comment by grasmash** [comment]
So, this is proving pretty hard to troubleshoot given that for < PHP 5.3,  the Phing dependencies are built in a completely differently way (without composer). This requires a separate local environment for troubleshooting.

@mrook Any thoughts on why these tests are failing? There are no errors or warnings being thrown.

**Comment by mrook** [comment]
@grasmash looks like the 5.2 tests are failing on master as well, segfaulting somewhere. I'm going to move the 5.2 tests to "allow_failure", then you can rebase against master.

**Comment by mikelohmann** [comment]
@grasmash: Thanks for caring about the PR.

**Comment by grasmash** [comment]
Looks like it's all passing!

**Comment by mikelohmann** [comment]
Cool!

**Comment by mrook** [comment]
@grasmash the code should at least not have parse errors in PHP 5.2, otherwise Phing will not start at all. Please refer to https://travis-ci.org/phingofficial/phing/jobs/77181882.

**Comment by grasmash** [comment]
@mrook Hm, this is a tough one. PHP 5.2 does not support namespacing syntax such as `\Symfony\Component\Yaml\Yaml`, but we require it in PHP 5.3 because Symfony namespaces the Yaml class. Simply calling `Yaml` will not suffice in PHP 5.3. 

Not quite sure what to do with this.

**Comment by grasmash** [comment]
@mrook Alright, I think we're set. 

I've refactored the code such that the class namespaces are defined via a string and called dynamically. This avoids PHP 5.2 syntax errors while also allowing us to use namespaces in 5.3+.

**Comment by grasmash** [comment]
@mrook Rebased the PR after your recent changes to composer.lock. Should merge cleanly now.

**Comment by mrook** [comment]
Almost there! Can you reformat the code to be PSR-2 compliant? Then I'll merge it, it looks good otherwise.

**Comment by grasmash** [comment]
@mrook All set!

**Comment by mrook** [comment]
Thanks!

**Pull request merged**
