### PR TITLE
[php 8.0 compatability] deprecated ReflectionParameter::getType()

### PR DESCRIPTION
**Pull request by Alexander1000**
Patch for revision 2.x
This is break on php 8.0

@siad007 @mrook

### CODE REVIEW

**Comment by jawira** [comment]
I think this was already fixed with #1440

**Comment by mrook** [comment]
That's right, but #1440 is against master (so 3.x).

**Comment by mrook** [comment]
@Alexander1000 thanks. Based on this I think I need to roll a 2.16.4, I've also merged your other PR. Are there any more 2.x blocking issues that you've found?

**Comment by Alexander1000** [comment]
Well, it seems so far everything that broke was found

**Pull request merged**
