### PR TITLE
Support FileList on PropertyTask, plus some test refactorings/additions

### PR DESCRIPTION
**Pull request by mpdude**
This cherry-picks from 616e19b3e17c7d51fba8acbff0ef53211fe33c2c and fb61ebe8960970d591c2943b3d1c1b3656d3cac5.

### CODE REVIEW

**Comment by mpdude** [comment]
@mrook Travis fails on HHVM only with

```
Execution of target "reports" failed for the following reason: : Test ERROR (testReadingFileListWithPrefix in class PropertyTaskTest): Array to string conversion
BUILD FAILED
: Test ERROR (testReadingFileListWithPrefix in class PropertyTaskTest): Array to string conversion
```

I don't have a HHVM at hand, so is there any way of making it output more debug information/a stack trace to figure out where exactly this conversion happens?

**Comment by mrook** [comment]
I actually get this error on a PHP install as well when testing against this branch.

Last lines of ```phing -debug -buildfile property.xml test-read-filelist-with-prefix```

```
property-test > test-read-filelist-with-prefix:

  +Task: property
    -calling setter PropertyTask::setPrefix()
    -calling creator PropertyTask::createFileList()
    -calling setter FileList::setDir()
    -calling setter FileList::setFiles()
 [property] Loading properties from /home/michiel/dev/phing/test/etc/system/util/filelist-1.properties
 [property] Loading properties from /home/michiel/dev/phing/test/etc/system/util/filelist-2.properties
Setting project property: prefix.test -> second
Adding reference: prefix.test -> PropertyValue
[PHP Error] Array to string conversion [line 267 of /home/michiel/dev/phing/src/Project.php]
Setting project property: prefix.array -> Array
[PHP Error] Array to string conversion [line 51 of /home/michiel/dev/phing/classes/phing/types/PropertyValue.php]
Adding reference: prefix.array -> PropertyValue
  +Task: echo
     [echo] assert second == second
```

**Comment by mpdude** [comment]
Strange, I thought I fixed this but it still fails on HHVM. When I run the buildfile directly as you showed above, the array is now correctly imploded.

**Comment by mrook** [comment]
[PHP Error] Array to string conversion [line 51 of /home/michiel/dev/phing/classes/phing/types/PropertyValue.php]

**Comment by mrook** [comment]
What's interesting is that travis-ci php builds seem to swallow the error, the hhvm build does not. My local php build also fails.

**Comment by mpdude** [comment]
Hooray, thanks @mrook!

**Pull request merged**
