### PR TITLE
Added PropertyFileParser for YAML formatted file

### PR DESCRIPTION
**Pull request by mikelohmann**
I added a YamlFileParser to be able to parser yaml files.

By that I extracted the Inifile parsing logic from Properties.php and introduced the FileParserInterface to be able to have several file parsers.

In PropertyTask.php I added a FileParserFactory to create based on the PhingFile::getExtension() of a file the file parser which is able to parse the file.

The default is still the ini file parse. So it does not break the former functionality.

The YamlFileParser flattens the array created from Symfony::YAML to be compatible to the existing properties mechanism and beeing able to access the property by a . separated string.

The existing functionality to convert commata separated lists into an array is supported with yaml files, too.

Everything is covered by unittests.

Example:

//yaml -file
testarea: testvalue
testarea1:
  testkey1: 1
  testkey2: 2
testarea2:
  [testvalue1, testvalue2, testvalue3]
testarea3: false
testarea4: true
testarea5:
  testkey1: [testvalue1, testvalue2]
testarea6:
  testkey1:
    testkey1: testvalue1
    testkey2: testvalue2
  testkey2:
    testkey1: testvalue1

will be flattened to:
$this->assertEquals('testvalue', $properties['testarea']);
$this->assertEquals(1, $properties['testarea1.testkey1']);
$this->assertEquals(2, $properties['testarea1.testkey2']);
$this->assertArrayHasKey(0, $properties['testarea2']);
$this->assertArrayHasKey(2, $properties['testarea2']);
$this->assertEquals('testvalue1', $properties['testarea2'][0]);
$this->assertEquals('testvalue3', $properties['testarea2'][2]);
$this->assertEquals(false, $properties['testarea3']);
$this->assertEquals(true, $properties['testarea4']);
$this->assertEquals('testvalue1', $properties['testarea6.testkey1.testkey1']);
$this->assertEquals('testvalue2', $properties['testarea6.testkey1.testkey2']);
$this->assertEquals('testvalue1', $properties['testarea6.testkey2.testkey1']);

### CODE REVIEW

**Comment by grasmash** [comment]
I'd love to get this committed. Oddly, this PR says that it's from an unknown branch, how can I continue work on this?

**Comment by mikelohmann** [comment]
Hi Matthew,

Great that you're willing to continue work on it. I had problems to merge the master into mine branch and if I remember it correctly the documentation generated automatically was missed in my commits. And the tests. I was not able in time to let them run through in my dev. That was the reason for not merging it, I think.

So from my point of view the documentation is the last block needed. And then let the tests run through.

Tell me if I can support you.

Regards 

Mike

**Comment by grasmash** [comment]
Hi Mike,

Thanks for chiming in, and for doing all of the heaving lifting! I've left your @author annotation in place :)

I think that the git issues are all sorted. It merges cleanly into master. I believe that I've also addressed the documentation issues. 

Additionally, the tests are passing for all version of PHP exception 5.2--that's the last issue to address. It's possible that the YAML component isn't compatible with PHP 5.2. Let me know if you have any thoughts on that!

**Comment by mikelohmann** [comment]
Hi,

Yes. For sure. I used the symfony component which needs indeed php >= 5.3 . Maybe it can be replaced by an older one? On the other hand: may be 5.2 is too old? What about increase the dependencies? Or somehow mark the tests and the yaml extension to be dependent on 5.3? 

It might be too much work to decrease the yaml component to be 5.2 compatible. 

What do you think?

Mike

**Comment by grasmash** [comment]
In my opinion, 5.2 should not be supported. It has long since reached end of life and is not supported by the PHP community any longer. I can modify the Travis build so that 5.2 is not tested, but I'd like approval from the maintainer. @mrook thoughts?

**Comment by mrook** [comment]
I agree, however dropping PHP 5.2 support would constitute a BC break and would mean bumping Phing to 3.0. Plans for that version exist (some serious refactoring / api / internal changes), and some work has already been done. You can ofcourse opt to rebase this PR to the 3.0 branch, but there is no release schedule, I do not anticipate 3.0 to be ready this year.

Regarding the task and the tests, there are a few tasks that will not run on PHP 5.2 (the Php Documentor 2 task for example), but the source should be valid PHP 5.2 (no namespaces, no short array syntax, etc.) and tests should at least run

**Comment by grasmash** [comment]
I can't find a version of the yaml component on GitHub or Packagist that supports PHP 5.2. This is a bit of an impasse for me. It seems that we should be able to add this specific feature without needing to used the massively refactored 3.0. How could we get this PHP 5.3+ feature into a Phing 2.x release? 

@mrook How do you feel about conditionally making the yaml parser to PHP 5.3+, and likewise conditionally executing the relevant tests?

**Comment by mrook** [comment]
@grasmash can I close this PR in favor of #453 ?

**Comment by grasmash** [comment]
Yes, thanks!

**Pull request closed without merging**
