### PR TITLE
Replaced while...each loops with foreach.

### PR DESCRIPTION
**Pull request by chasepeeler**
each() is deprecated in PHP 7.2

### CODE REVIEW

**Comment by siad007** [comment]
@chasepeeler thanks!

**Comment by chasepeeler** [comment]
@siad007 No problem! I'm going through my code base preparing to upgrade from 7.0 to 7.3. Anytime I find something like this or the previous PR, I'm going to at least fork the repo and make the updates on my fork - which I can then use in composer instead of the main repo, if necessary. I figure small little things like this are no-brainers for a PR, though. The fact that you merge them in means I can continue to use the main repo too.

**Comment by siad007** [comment]
@chasepeeler every helping hand to make this project greater than it is already, is very welcome. 😃

**Comment by kenguest** [comment]
thanks @chasepeeler  - that's the joy of opensource and pushing fixes upstream - everybody benefits!

:-)

**Pull request merged**
