### PR TITLE
Add exclude option to FileSyncTask.

### PR DESCRIPTION
**Pull request by Polzme**
Add exclude option to rsync command.

### CODE REVIEW

**Comment by mrook** [comment]
Thanks for the PR! Can you add a few lines to the user guide (docs/docbook5/en/) for the new attribute?

**Comment by mpdude** [comment]
I might be missing something, but this seems to lack at least a setter method for the new field?

And tests would be nice :)

**Comment by mrook** [comment]
Fuck, totally missed that. I'll add a setter.

**Comment by mpdude** [comment]
A test would have shown it.

To be honest, I don't write tests in real life. Just here for Phing.

**Comment by mrook** [comment]
I usually always write tests, Phing is usually an exception :)

**Pull request merged**
