### PR TITLE
Moved ResolvePathTask to PropertyTask.

### PR DESCRIPTION
**Pull request by siad007**
Moved function of
`<resolvepath propertyName="resolved.dir" dir="."/>`
to
`<property name="resolved.dir" location="."/>`
and deprecated the use of it.

### CODE REVIEW

**Comment by mrook** [comment]
I like this! Maybe add ```setLocation``` to increase compatibility with Ant?

**Comment by siad007** [comment]
Would be awsome but unfortunaly setLocation is a forbidden word. see IntrospectionHelper:
```php
    // There are a few "reserved" names that might look like attribute setters
    // but should actually just be skipped.  (Note: this means you can't ever
    // have an attribute named "location" or "tasktype" or a nested element named "task".)
    if ($name === "setlocation" || $name === "settasktype" || $name === "addtask") {
        continue;
    }
```

**Comment by mrook** [comment]
Good point, may have to think about that.

**Comment by mrook** [comment]
Yeah we can't actually get rid of that. ```setLocation``` is already defined in ```ProjectComponent.php```. This works in Ant because of method overloading.

**Comment by siad007** [comment]
@mrook this would work - what do you think?

**Pull request closed without merging**
