### PR TITLE
Removed PHP4-style constructor

### PR DESCRIPTION
**Pull request by janlanger**
For better compatibility with PHP 7

### CODE REVIEW

**Comment by VasekPurchart** [comment]
@mrook could you please consider releasing new version of Phing? PHP 7 is around the corner and the warning fixed by this PR keeps popping up everywhere :) There is also handful of other new commits in master.

**Comment by janlanger** [comment]
@VasekPurchart The fix is in 2.12 released on 28 Aug ;)

**Comment by VasekPurchart** [comment]
Huh, thx, I somehow missed it :(

**Comment by mrook** [comment]
:) thx @janlanger 

@VasekPurchart regardless I'll push a 2.13 in a week or two tops :)

**Pull request merged**
