### PR TITLE
Added property file generation for VersionTask

### PR DESCRIPTION
**Pull request by siad007**
Added property file generation and made file name and property optional.

### CODE REVIEW

**Comment by mrook** [comment]
Would it make sense to extend/adapt the existing version task (and possibly aliasing that) instead of creating a new task?

**Comment by siad007** [comment]
@mrook Just moved the main function from the previous buildNumberTask to the existing VersionTask.

**Comment by siad007** [comment]
@mrook tests added and updated documentation

**Comment by mrook** [comment]
@siad007 can you rebase this?

**Comment by siad007** [comment]
@mrook rebased ;)

**Comment by siad007** [comment]
Related to #711

**Pull request merged**
