### PR TITLE
[patch for 2.16.2][php7] Deprecated: Array and string offset access syntax with curly braces is deprecated

### PR DESCRIPTION
**Pull request by Alexander1000**
Deprecated: Array and string offset access syntax with curly braces is deprecated

### CODE REVIEW

**Comment by Alexander1000** [comment]
Hello guys!
I make patch for release 2.16.2 with compat php 7.4
Review please: @mrook @siad007

**Comment by siad007** [comment]
> 
> 
> Hello guys!
> I make patch for release 2.16.2 with compat php 7.4
> Review please: @mrook @siad007

@Alexander1000 Thanks for your contribution.
This changes should be reviewed by @mrook for the
decision not to test the 2.x branch on PHP 5.3 - PHP 5.5

**Comment by mrook** [comment]
I'll take a look at it soon. Thanks all!

**Comment by mrook** [comment]
@Alexander1000 can you elaborate on the changes to the git docs and tests?

**Comment by siad007** [comment]
> 
> 
> @Alexander1000 can you elaborate on the changes to the git docs and tests?

@mrook this changes have been made some time ago on the 3.x branch to support git >= 2.15.0 which is needed for travis?! (just a guess)

**Comment by Alexander1000** [comment]
@siad007, It seems that older versions are not supported in Travis
In build logs:
> Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-5.5.tar.bz2
> $ curl -sSf --retry 5 -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
> curl: (22) The requested URL returned error: 404 Not Found

@mrook 
> this changes have been made some time ago on the 3.x branch to support git >= 2.15.0 which is needed for travis?!

Yes

**Comment by mrook** [comment]
Thanks! I'll try to roll 2.16.2 soon.

**Pull request merged**
