### PR TITLE
Solve ticket #1134 and add color support on phar version (all platforms)

### PR DESCRIPTION
**Pull request by llaville**

### CODE REVIEW

**Comment by mrook** [comment]
Thanks! Do we need to apply the same logic to bin/phing and/or phing.bat?

**Comment by llaville** [comment]
There is no need to modify the phing.bat, but yes we probably apply the same update on bin/phing.

So perharps a better solution will be to modiy only the bin/phing and not the phing-stub.php (that calls bin/phing)

**Comment by llaville** [comment]
uhm forget to see that the `phing.bat` called directly the `bin/phing.php` and not the `bin/phing`

**Comment by llaville** [comment]
The solution will be to put the modification inside `bin\phing.php` the common script to all enties.
Give me your feedback

**Comment by phingauto** [comment]
Yes that sounds like a good solution. Can you adapt this pr to do that or open a new one?

**Comment by llaville** [comment]
Sure, I can do it, and in a new PR. I can't adapt this one, so I'll close it, and open a new one

**Comment by llaville** [comment]
See new PR #409

**Pull request closed without merging**
