### PR TITLE
Clear PullRequest #309 to allow phing to manage Composer Autoloader

### PR DESCRIPTION
**Pull request by corretge**
I write a new and clear PR for the Composer integration.

To test it, create a new one project with a **composer.json** like:

```
{
        "require": {
        "corretgecom/phing-base64": "dev-master"
    }
}
```

And a **build.xml** file like:

```
<?xml version="1.0" ?>
<project basedir="." default="list">

    <!-- Sets the DSTAMP, TSTAMP and TODAY properties -->
    <tstamp/>

    <target name="list" description="List targets">
        <exec command="phing -l" level="verbose" passthru="true" />
    </target>

    <import file="vendor/bin/corretgecom.qgpl.base64.xml" optional="false" />

</project>
```

Then, execute:

```
composer update
phing 
```

The targets _imported_ will be showed.

The tasks:
- console.qgpl.base64.decode
- console.qgpl.base64.encode

are defined at

```
vendor/corretgecom/phing-base64/lib/
└── Corretgecom
    └── Phing
        └── Qgpl
            └── Base64
                ├── DecodeTask.php
                └── EncodeTask.php
```

### CODE REVIEW

**Comment by corretge** [comment]
The build is broken because:

PHP 5.2: Fatal error: Undefined class constant 'Phar::NONE' in /home/travis/build/phingofficial/phing/classes/phing/Project.php on line 722

PHP 7: PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /home/travis/build/phingofficial/phing/vendor/pear-pear.php.net/PEAR/PEAR/Config.php on line 650
Parse error: syntax error, unexpected 'new' (T_NEW) in /home/travis/build/phingofficial/phing/vendor/pear-pear.php.net/PEAR/PEAR/Config.php on line 650

**Comment by mrook** [comment]
PHP 5.2 compatibility should be retained for Phing 2.x

PHP 7 compatibility is nice but not required, plus this is a PEAR class.

**Comment by corretge** [comment]
For PHP 7 compatitiblity we should wait a new version of pear-pear.php.net

For PHP 5.2 compatibility... I will pray tonight ;-)

**Comment by corretge** [comment]
Hi @mrook I found the problem with Phar and PHP 5.2 and fix it adding @requires PHP 5.3.2 as the other tests in the same file. But I can't undestand why only my PR had troubles.

**Comment by corretge** [comment]
@mrook ping

**Comment by mrook** [comment]
Hi @corretge - sorry it took me this long to check & reply to your PR. Is this still a valid PR? Phing 3.0 will only be available through composer or as a .phar.

**Comment by corretge** [comment]
Hi @mrook I think that it's not necessary. Maybe could be useful for 3.0 the way to locate files checking composer.json path configuration, if you change paths inside.

**Pull request closed without merging**
