### PR TITLE
Removed IterableFileSet

### LINKED ISSUE #531: Integrate SPL into Phing (Trac #281)
Integrate [http://ru.php.net/manual/en/book.spl.php SPL] features (Iterator, ArrayAccess...) to Phing, as [http://phing.tigris.org/servlets/ReadMsg?list=dev&msgNo=782 discussed].

Migrated from https://www.phing.info/trac/ticket/281

``` json
{
    "status": "new", 
    "changetime": "2016-10-07T08:28:55", 
    "description": "Integrate [http://ru.php.net/manual/en/book.spl.php SPL] features (Iterator, ArrayAccess...) to Phing, as [http://phing.tigris.org/servlets/ReadMsg?list=dev&msgNo=782 discussed].", 
    "reporter": "alexeyshockov", 
    "cc": "mp@webfactory.de", 
    "resolution": "", 
    "_ts": "1475828935569836", 
    "component": "phing-core", 
    "summary": "Integrate SPL into Phing", 
    "priority": "major", 
    "keywords": "spl", 
    "version": "", 
    "time": "2008-09-30T12:16:02", 
    "milestone": "4.0", 
    "owner": "alexeyshockov", 
    "type": "enhancement"
}
```

### PR DESCRIPTION
**Pull request by siad007**
Closes #531

### CODE REVIEW

**Comment by mrook** [comment]
@siad007 can you resolve the conflicts?

**Comment by MaXal** [comment]
In our tests we now have the following error:
Fatal error: Declaration of ZendGuardFileSet::getFiles(Project $p, $includeEmpty = true) must be compatible with AbstractFileSet::getFiles(...$options) in /app/vendor/phing/phing/classes/phing/tasks/ext/zendguard/ZendGuardFileSet.php on line 32

**Comment by MaXal** [comment]
Now we have:
Parse error: syntax error, unexpected '=', expecting variable (T_VARIABLE) in /app/vendor/phing/phing/classes/phing/tasks/ext/zendguard/ZendGuardFileSet.php on line 23

**Comment by MaXal** [comment]
You've missed the $ before the parameter name. Don't you use PhpStorm:)?

**Comment by mrook** [comment]
Thanks for pointing that out @MaXal, it should be fixed now. As a general rule, I recommend not using phing master directly (if you can avoid it). We try to avoid breaking it, but that's not always possible.

**Comment by mrook** [comment]
@MaXal ah! I did not realize you were part of the PhpStorm team, welcome :-)

**Pull request merged**
