### PR TITLE
Fixing -propertyfile option and adding yaml support for it.

### PR DESCRIPTION
**Pull request by grasmash**
I found that passing `-propertyfile <filename.yml>` was not setting the properties values as expected. The first reason for this was that the command option assumes that the file will use the IniParser. This has been addressed and did not support .yml files.

However, after adding yaml support I found that the expected property values still were not set. I'm not sure why. The passed `-propertyfile` was not overriding existing property values--merely defining new ones. Regardless, adding them to the $definedProps array seems to have solved it.

For background, I was using the `-f build.xml` option as well as loading various property files via the `<property file="<filename>" />` method. I'm not sure if this could be related.

### CODE REVIEW

**Comment by grasmash** [comment]
I found that passing `-propertyfile <filename.yml>` was not setting the properties values as expected. The first reason for this was that the command option assumes that the file will use the IniParser. This has been addressed and did not support .yml files.

However, after adding yaml support I found that the expected property values still were not set. I'm not sure why. The passed `-propertyfile` was not overriding existing property values--merely defining new ones. Regardless, adding them to the $definedProps array seems to have solved it.

For background, I was using the `-f build.xml` option as well as loading various property files via the `<property file="<filename>" />` method. I'm not sure if this could be related.

**Comment by grasmash** [comment]
@mrook Does this pull request require any changes before being merged?

**Comment by mrook** [comment]
Overriding existing property files sounds like a backwards-incompatible change, so I'm not sure that's something we can merge. The fixes look fine.

**Comment by grasmash** [comment]
What if we introduced an additional option to specify whether the build file should override defined properties? Would that suffice to make backwards compatible?

E.g., `phing -propertyfile filename.yml -propertyfileoverride

**Comment by mrook** [comment]
That could work :)

**Comment by grasmash** [comment]
The errors in the Travis output seem related to an SVN checkout issue, which seems unrelated to changes made in this PR:
```
Server sent unexpected return value (429 Too Many Requests) 
```

@mrook I've introduce the new -propertyfileoverride option as discussed. Please let me know if any further changes are required.

**Comment by CashWilliams** [comment]
Looks good to me. I'm running this branch for some builds and working well.

**Comment by mrook** [comment]
Looks good. One last thing: can you clean up the indentation (should be 4 spaces per level of indentation) and squash the commits?

**Comment by grasmash** [comment]
@mrook Updated and squashed.

**Comment by mrook** [comment]
Thank you!

**Pull request merged**
