### PR TITLE
[WIP] extend Coding Style

### PR DESCRIPTION
**Pull request by mimmi20**
This PR is still work in progress.

### CODE REVIEW

**Comment by kenguest** [comment]
What exactly is this about? I don't believe there's any intent on changing the Phing codebase from established PSRn Coding Standards... Please correct me if I'm wrong.

**Comment by mrook** [comment]
You're not wrong @kenguest, there's no intent to change that. Can you clarify @mimmi20 ?

**Comment by mimmi20** [comment]
The Doctrine coding standard and the underlying Slevomat coding standard are based on PSR 2. I want to use this to force strict types, type hints (as much as possible), doc block formating and single quotes.

Because PSR 2 is different from PSR 12, there are some rule conflicts I have to solve. After this I want to play around with the rules a bit.

**Comment by siad007** [comment]
IMO it makes no sense to downgrade from PSR12 to PSR2

Thomas Müller <notifications@github.com> schrieb am Di. 17. Dez. 2019 um
17:29:

**Pull request closed without merging**
