### PR TITLE
improve phing composer and relationship

### PR DESCRIPTION
**Pull request by corretge**
Allow to load composer autoload.php file when phing is executed in a global scope
Allow to place composer autoload.php file in a different folder setted by config->vendor-dir
Allow to ignore errors when taskdef require a class and autoload.php do not exist, in example when a phing task is executed by composer pre-install-cmd.

my environment can not pass all the tests, there are a lot of dependencies and I don't know all. Can you test https://github.com/corretgecom/phing.git before to merge the pull?

thanks

### CODE REVIEW

**Comment by mrook** [comment]
Hi @corretge, can you clean up this PR (remove unrelated commits, squash the rest) and rebase against current master? Thanks

**Comment by corretge** [comment]
Ops sorry for the delayed anser.

I have a problem, I can't test on my development environment because crash and I use travis as tester. Then I need to push commits, and I can't (well, I don't know) how to rebase interactive pushed commits.

Maybe create a package like this https://atlas.hashicorp.com/rasmus/boxes/php7dev could be interesting to be sure that all the developers have the same environment.

**Comment by mrook** [comment]
Hi @corretge . I'm not sure I understand your problem. If you clone phing and do a composer install you should most of the deps to run the tests succesfully, you shouldn't have to require travis.

**Comment by mpdude** [comment]
What exactly is the goal of this PR?

**Comment by corretge** [comment]
@mrook my develop workstation is a Mac. Yesterday I upgrade memory and I can create a vagrant machine to test.

**Comment by mrook** [comment]
@corretge should not be a problem, PHP/composer run fine on Mac's.

**Comment by corretge** [comment]
@mpdude the goal is allow Phing to use composer autoload. Phing could be installed in a global scope, and you can configure composer in a different folder than vendor. My PR fix this kind of things.

**Comment by corretge** [comment]
@mrook yes I know :) I'm working with composer on my Mac, thats the reason of the PR :) The problem that I have is with the requirements for the Phing package.

**Comment by mrook** [comment]
I see. Those changes (such as the hipchat integration, changes to the README.md etc) do pollute the PR a lot. Can you clean those up, or open a new PR with only the necessary changes?

**Comment by corretge** [comment]
I close this PR and I will create another one more clear.

**Pull request closed without merging**
