### PR TITLE
Task webserver

### PR DESCRIPTION
**Pull request by adrianbroher**
Hello Phing devs,

this pull request contains a new task, which exposes the PHP built-in HTTP server. The purpose of this could be to run feature tests or other tasks that require a running HTTP server without the need to set up a full fledged HTTP server like Apache.

I'm using this task in another project for serveral month now and so far the implementation did work well and I hope that it can be useful for the phing upstream. However, the implementation had only limited testing on a single linux platform and was written by me for me so there is no proper documentation available yet.

I would like to ask for guidance and review on this task to make it acceptable for inclusion into Phing.
# Features

The `webserver` task allows developers to run an instance of built-in PHP (>= 5.5) webserver and executing abitary tasks while web server instance is running. IP-address, port, document root and a routing script can be optionally set by attributes. Also it is possible to set ini configurations with child `config` nodes. The tasks that should be executed with a running web server instance available are placed inside the `tasks` node.
# Requirements
- The tasks needs to be run with PHP 5.5 or later (maybe works even with PHP 5.4).
# Usage

``` xml
<webserver address="127.0.0.1" port="8080" docroot="${project.basedir}/src" router="${project.basedir}/src/router.php">
    <config name="auto_prepend_file" value="${project.basedir}/some-prepend-file.php" />
    <tasks>
        <sometask />
        <someothertask />
    </tasks>
</webserver>
```
# Missing parts
- The current task implementation was only tested on Linux with a recent PHP version. It may or may not work on other platforms and may or may not work with PHP 5.4 (the version that introduced the built-in web server).
- There are no unit tests available yet.
- There is no end user documentation available yet.
- All notices, messages and errors from the spawned web server are thrown away silently. I wanted to implement a filter for those and inject the output properly into the output of the parallel running tasks. So far I haven't found a way to hook into the Phing logging to intercept both the web server output and the embedded tasks to create sequencial and correct output.
- Maybe there is more code reuse from internal Phing classes possible.
# TODO
- [x] Make the code PHP 5.2 compatible
- [ ] Write unit tests
- [ ] Write user documentation
- [x] Implement a multiplexer for combining the phing tasks and php server output
- [ ] Implement a configurable filter for filtering out superfluous php server output

### CODE REVIEW

**Comment by mrook** [comment]
Hi! Thanks for the concise & interesting PR! I'll check in detail asap, but, apart from the points you already mentioned, Phing 2.x is PHP 5.2+ compatible. This does not mean that the task should actually function on < 5.4 (which it can't), but the class should parse and Phing should run with the task enabled.

**Comment by adrianbroher** [comment]
Rebased pull request to current master and added some way to inject the web server log messages into the PHING logging system.  Now I need a way to filter out log messages by attributes (the log entries are split up into the HTTP response code, the requested url, client IP and port, a log level and a message).  Are there some classes in the project that I could reuse to describe some kind of filter rules in a phing build.xml?

**Comment by mrook** [comment]
@adrianbroher not currently no, there's only Project::log($message, $level).

**Comment by adrianbroher** [comment]
@mrook 

I hadn't time to work on this since my last message.  Is there anything I need to know regarding the `needs update` tag?

**Comment by mrook** [comment]
Hi @adrianbroher, the tag is regarding the open todo's on this PR. Are you able to perform any work on this PR in the short to medium term?

**Comment by adrianbroher** [comment]
> Are you able to perform any work on this PR in the short to medium term?

I you mean with medium term like in the next three month I really doubt so and to be honest I currently don't feel like fighting with anything PHP related in general, but I still want to finish this PR sometime in the future.

**Comment by mrook** [comment]
Ok, thanks. I'll close it for now, you can re-open the PR at any time, or create a new one. Thanks again!

**Pull request closed without merging**
