### PR TITLE
Dynamic path for composer task

### PR DESCRIPTION
**Pull request by verbruggenalex**
It would be a nice feature to have the phing composer task check if a composer installation is available to execute the command with if no composer executable path is set.

### CODE REVIEW

**Comment by mrook** [comment]
Related to #558.

**Comment by verbruggenalex** [comment]
Would it be a good idea to implement a try catch on the command with the provided composer path and then try finding a path if that fails? That would cover the user entering a wrong path. But then the user would not be aware of that mistake.

**Comment by verbruggenalex** [comment]
I moved the path check to the getComposer function and cleaned up the class a bit.

**Comment by verbruggenalex** [comment]
Mind giving me a new review @mrook ?

**Comment by mrook** [comment]
Can you squash the commits? The PR is a little noisy this way :)

Anyway:

* I see a lot of unrelated changes (docblock modifications etc.)
* Instead of checking against `php_uname` you can perhaps reuse the `host.fstype` property

**Pull request merged**
