### PR TITLE
[php 8.0 compat] fix php warning:  Private methods cannot be final

### PR DESCRIPTION
**Pull request by Alexander1000**
Private methods cannot be final as they are never overridden by other classes

### CODE REVIEW

**Comment by Alexander1000** [comment]
@mrook @siad007 review please

**Comment by siad007** [comment]
And in master https://github.com/phingofficial/phing/blob/master/classes/phing/listener/AnsiColorLogger.php

**Comment by Alexander1000** [comment]
need to 2.16.x versions

**Comment by mrook** [comment]
We've sort of stopped with releasing 2.16.x versions. Is this a showstopper?

**Comment by mrook** [comment]
It's only a warning, right?

**Comment by Alexander1000** [comment]
yes, only warnings
not features

**Comment by mrook** [comment]
Ok thanks. In that case I'm going to leave this one for now. We're working on a release candidate for 3.x, that has priority for us. Thanks for reporting!

**Comment by Alexander1000** [comment]
how long to wait for release 3.x?

**Pull request merged**
