### PR TITLE
Fixed https://www.phing.info/trac/ticket/1190

### PR DESCRIPTION
**Pull request by siad007**
PropertyRegexTask uses `Regexp()` now.
Fixed https://www.phing.info/trac/ticket/1190

### CODE REVIEW

**Comment by mrook** [comment]
@siad007 is it possible to retain the limit parameter? That way it won't be a BC breaking change

**Comment by siad007** [comment]
@mrook done

**Comment by mrook** [comment]
Hmm, I guess I should have been more clear, sorry :) The PregEngine class uses preg_replace, which still supports limit. By exposing that in that class, the interface and the RegExp class we can still support the limit parameter from the PropertyRegexTask. Thoughts?

**Comment by siad007** [comment]
No problem - so i would extend the RegExp and PregEngine classes then to support the limit parameter. Would this be an option? I will give it a try in the evening.

**Comment by mrook** [comment]
Yup I think that'd work, thanks

**Comment by siad007** [comment]
@mrook done

**Pull request merged**
