### PR TITLE
Added runtarget task.

### PR DESCRIPTION
**Pull request by siad007**
Phing task that runs a target:

``` xml
  <target name="run">
    <runtarget target="anotherTarget" />
  </target>

  <target name="anotherTarget">
    <echo msg="THIS COMES FROM ANOTHER TARGET"/>
  </target>
```

### CODE REVIEW

**Comment by grasmash** [comment]
How does this differ from phingcall?

**Comment by siad007** [comment]
The main difference is the scope, which means that any property it sets will not be visible to the build that used `<phingcall>`. `<runtarget>` does not create a new Project, so all properties set are visible to the "caller". So there would be an performance boost if we take `<runtask target="foo.bar"/>` instead of `<phingcall inheritrefs="true"/>` but in fact it would be cleaner/saver to use the build in phingcall, that's why i moved this to the ext/optional tasks.

**Comment by siad007** [comment]
Related to #576 - reminder to myself: needs rebase

**Comment by mrook** [comment]
@siad007 I'd like to go ahead and merge this, but we probably need to include something in the documentation to warn users about the potential pitfalls/dangers of using ```runtarget``` vs ```phingcall```, what do you think?

**Comment by siad007** [comment]
@mrook I will add a note in the documentation.

**Pull request merged**
