### PR TITLE
Adds ImportMultiTask.

### PR DESCRIPTION
**Pull request by nickschuch**
**Use case**

I pull down alot of different build.xml files with composer. I don't want to have to add multiple import references, especially if I am adding a new library.

Giving Phing and almost "autoload" kind of functionality.

**Solution**

Create a ImportMultiTask object for this case.

```
<import-multi files="vendor/previousnext/*/build*.xml" optional="true" />
```

**Help**

Can I please get some guidance on:

* If this could be committed to Phing.
* How I can get it over the line so I can be committed.

### CODE REVIEW

**Comment by nickschuch** [comment]
Will take a look at this today.

**Comment by nickschuch** [comment]
Hi @mrook, sorry for the deploy on this one. I cleaned up the commits and added unit tests for checking if the files get picked up, assuming the remaining unit tests also cover execution of targets etc.

Lets me know if there is anything else you require prior to commit :)

**Comment by mrook** [comment]
Thanks, I'll take a look at it soon!

**Comment by nickschuch** [comment]
Anything I can do to help this one along?

**Comment by mrook** [comment]
I've been extremely busy and haven't been able to spend any time on Phing. Hope to get to it soon.

**Comment by mrook** [comment]
Looks good @nickschuch, but it looks like the documentation commit(s) are missing from the PR? The user guide entry for the import task needs to be updated as well.

**Comment by nickschuch** [comment]
No worries, Ill have that updated in the next 1hr.

**Comment by nickschuch** [comment]
Any changes you would like to see on these docs?

**Comment by nickschuch** [comment]
Can I get an indicator on when a new release might come out?

**Comment by mrook** [comment]
@nickschuch a (very) rough estimate can be found on https://www.phing.info/trac/roadmap

**Comment by nickschuch** [comment]
No worries, thankyou so much! Woohoo!!!

**Pull request merged**
