### PR TITLE
Use an absolute path (using __DIR__) in test/bootstrap.php

### PR DESCRIPTION
**Pull request by mpdude**
This makes it possible [for me, at least] to run PHPUnit from my IDE.

### CODE REVIEW

**Comment by siad007** [comment]
@mpdude Does it not make more sense to use `dirname(__FILE__)` instead? `__DIR__` is >= PHP 5.3 .

**Comment by mpdude** [comment]
To provide PHP 5.2 support?

**Comment by siad007** [comment]
yes :) or did i miss something...

**Comment by mpdude** [comment]
No, probably not... It's just that I though I was the last man on earth still running 5.3 so...

**Comment by mrook** [comment]
This is a PR against the 3.0 branch which is 5.4+, __DIR__ can be used.

**Pull request merged**
