### PR TITLE
Added DisableInputHandler

### PR DESCRIPTION
**Pull request by MaximilianKresse**
Implementation for #1003 
Just a simple dummy input handler to disable console interaction.

### CODE REVIEW

**Comment by MaximilianKresse** [comment]
I added it to the Command Line Arguments documentation page. But a test is a little bit more complicated because it does nothing by itself =)

**Comment by siad007** [comment]
> I added it to the Command Line Arguments documentation page. But a test is a little bit more complicated because it does nothing by itself =)

@MaximilianKresse you could write a test with an `exec` task to call phing as an executable with the new input handler as an argument and an additional buildfile, where you have an input task and an echo task to assert against the echo text in the logs. What do you think?

**Comment by MaximilianKresse** [comment]
I added a test. I have oriented myself to the ConsoleInputHandler. There was a bug because of some unexpected handling of default values (the input handler have to care about the default value).

**Comment by siad007** [comment]
Thanks!

**Pull request merged**
