### PR TITLE
Add foreachparallel-task to phing

### PR DESCRIPTION
**Pull request by mkrauser**
Hi guys,

since phing has a ParallelTask and a ForeachTask, it makes sense to have a ForeachParallelTask too. I've developed a standalone-library for this a while ago (https://github.com/mkrauser/phing-foreach-parallel-task). 
I would love to see it in Phing-Core. Since the new Task inherits from ForeachTask, I had to make some changes to it as well to make it more open for inheritance.

Thanks for the awesome work!

### CODE REVIEW

**Comment by mrook** [comment]
Hm, I like the idea very much, but wouldn't it be more interesting to see if the parallel task can be refactored (extract a few classes, etc.) and add a "parallel=true|false" option to the foreach task?

**Comment by mkrauser** [comment]
@mrook I thought about that as well, but I did not want to touch the foreach-task before talking to core-devs. If you like, I can work on that

**Comment by mrook** [comment]
That would be great!

**Comment by mkrauser** [comment]
@mrook I've updated the pull request to implement concurrency in foreach-task. 

There are two things that bother me:
1. First, even if the tasks are not run in parallel, a new callee is created for every iteration. I can change that, but the code will become a little unreadable
2. The parallelManager is passed to process(...) as parameter. Personally I would rather implement this as class-property.

Please take a look an let me know your thoughts.

**Comment by mrook** [comment]
Thanks! I'll have a look soon (pretty busy at the moment).

**Comment by mrook** [comment]
Hi @mkrauser sorry it took me so long to review/reply. I like the general gist of it, but I have a few minor points:

- there is some code duplication, this block is repeated and can probably be re-used by extracting it to a method:
                if($this->parallel === true) {
                    $worker = new DocBlox_Parallel_Worker(
                        array($callee, 'main'),
                        array($callee)
                    );
                    $parallelManager->addWorker($worker);
                } else {
                    $callee->main();
                }
- parallelManager can be a class property (as you stated yourself)
- should createCallee be public?
- I'm not against marking more properties as protected, but you add a few private properties in your commit; what should we do here?

**Comment by mkrauser** [comment]
Hey @mrook, 
it also took me a while, I was pretty busy with other projects as well.

I've update the PR to reflect your suggestions. There's only one thing that I'm not entirely happy with: the name of configureCallee(...), somehow It does not feel right. 
If you have a suggestion for a better name or any other improvements, please get back to me.

Thanks for your review!

**Comment by mrook** [comment]
Thanks for your contribution! Closing this because of inactivity, please re-open or submit a new pull request if you have time to fix the mentioned issues.

**Pull request closed without merging**
