### PR TITLE
Fixed AvailableTaskTest execution under windows.

### PR DESCRIPTION
**Pull request by siad007**
Symlink aware tests will not work on windows.

### CODE REVIEW

**Comment by mrook** [comment]
Hmm I thought symbolic links are supported on recent Windows versions? Haven't tested this myself yet.

**Comment by siad007** [comment]
The main problem here is that the shell needs administration previlegs for running the unit tests, which in my opinion is not the best solution.

**Comment by mrook** [comment]
Hmm. Ideally I'd like to avoid that too, but if that's the only way to test if we can create symlinks on Windows..

**Comment by siad007** [comment]
Ah i see, then i will close this issue.

**Pull request closed without merging**
