### PR TITLE
Adding 0 and 1 strings as true and false values in StringHelper.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
I find that people commonly pass "0" and "1" as strings for boolean properties. These should be evaluated as false and true.

**Comment by grasmash** [comment]
@mrook I believe this is a false test failure. I this PR acceptable? It seems like a minor, backwards compatible change.

**Comment by mrook** [comment]
@grasmash can you rebase?

**Comment by mrook** [comment]
Also, I'm trying to decide whether this is a BC break or not ;-)

**Comment by grasmash** [comment]
Rebased!

**Comment by siad007** [comment]
Related to #261

**Comment by mpdude** [comment]
:+1: for this change

**Comment by mrook** [comment]
@grasmash I think this would mean a BC break. Shouldn't be that much of a problem, I'm planning to release 3.0 early next year.  Can you rebase this PR against the 3.0 branch?

**Pull request merged**
