### PR TITLE
update to support phpcs v2.2.*

### PR DESCRIPTION
**Pull request by alexbumbacea**
Fixes error 
[PHP Error] Argument 3 passed to PHP_CodeSniffer_Reporting::printReport() must be of the type array, string given, called in vendor/phing/phing/classes/phing/tasks/ext/PhpCodeSnifferTask.php on line 537 and defined [line 222 of vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php]

### CODE REVIEW

**Comment by mrook** [comment]
Thanks. Will phpcs 1.5.x still function after this change?

**Comment by alexbumbacea** [comment]
phpcs 1.5.x will not work any more.

Please consider that phpcs 2.2.0 is the latest stable running version also on pear, so i think it will be ok to start using it.

**Comment by mrook** [comment]
I would like to keep 1.5.x working, users may not have upgraded.

**Comment by throup** [comment]
I only discovered this pull request after implementing a similar fix myself. See #379 for a fix which preserves backward compatibility.

**Comment by mrook** [comment]
Closing because of #379, thanks for your efforts @throup and @alexbumbacea !

**Pull request closed without merging**
