### PR TITLE
Added isReadable / isWritable selectors

### PR DESCRIPTION
**Pull request by siad007**
Example usage:
```
<fileset dir="${src}" includes="**/*.php">
            <readable/>
</fileset>
```

### CODE REVIEW

**Comment by mrook** [comment]
@siad007 can you add unit tests?

**Comment by siad007** [comment]
@mrook it would be helpful writing cross os tests with #454 merged.

**Comment by mrook** [comment]
@siad007 now that #454 is merged, are unit tests of any use?

**Comment by siad007** [comment]
I will add some unit tests soon.

Am Montag, 7. Dezember 2015 schrieb Michiel Rook :

**Comment by siad007** [comment]
@mrook unit tests added :)

**Pull request merged**
