### PR TITLE
Add OpenTask

### LINKED ISSUE #1606: Task to open files and URLs
**Is your feature request related to a problem? Please describe.**

Hi, very often I have to open URLs with Phing, typically each time I launch my docker-compose.

What I do in almost all my projects is: 

```xml
<exec executable="xdg-open" spawn="true">
  <arg value="http://web.${dc.project-name}.test/"/>
</exec>
```

I also use `xdg-open` to open files, for example after a pdf is generated.

**Describe the solution you'd like**

So, I think It would be cool to have a task to do this. Something like:

```xml
<open path="http://web.${dc.project-name}.test/"/>
<open path="resources/report.pdf"/>
```

**Describe alternatives you've considered**

The alternative to `<open/>` is to continue to use `ExecTask`.

Note that Composer also uses `xdg-open` when you type `$ composer home`.

**Additional context**

To be honest I already worked on this last year, you can found it in <https://gitlab.com/jawira/phing-open-task>.
Sadly I don't use it because it's not bundled with Phing and I don't like when PhpStorm marks unknown tasks as errors :P

Please consider adding `OpenTask` to Phing (I can create the PR). Otherwise feel free to close this issue :)

### PR DESCRIPTION
**Pull request by jawira**
`OpenTask` opens a file or URL in the user's preferred application.

```xml
<open path="requirements.pdf"/>   // open pdf reader
<open path="http://localhost/"/>  // open browser
```

This should work in Linux, IOS and Windows. But, to be honest I have only tested this task in Ubuntu because I don't own an Apple nor a Windows PC.

Closes #1606

### CODE REVIEW

**Comment by mrook** [comment]
Thanks @jawira. Can this be automatically tested somehow? And can you write documentation in https://github.com/phingofficial/guide?

**Comment by jawira** [comment]
> Thanks @jawira. Can this be automatically tested somehow? And can you write documentation in https://github.com/phingofficial/guide?

I will add some unit tests, if that's enough for you. I'm going to update the documentation as well.

**Comment by jawira** [comment]
@mrook I wrote some tests, surprisingly MacOS and Windows tests pass, but Ubuntu tests don't :( :( :(

I think the problem is `xdg-open` is not installed in `ubuntu-latest` image. Should I manually install `xdg-open` in Ubuntu's image? Any other suggestion?

**Comment by siad007** [comment]
@jawira the problem with ubutu is that it is a plain headless image with no desktop preinstalled.

* Either you use `ubuntu:latest` and install the dependencies you need or
* you use another image with preinstalled desktop such like `dorowu/ubuntu-desktop-lxde-vnc`

For our test setup I would suggest to install xdg-open by adding following lines to the github action:

```yaml
- name: Install xdg-utils
  run: sudo apt-get install xdg-utils
```

**Comment by jawira** [comment]
@siad007 I think OpenTask is ready.

- I installed xdg-open on Ubuntu image. I used /usr/bin/true (this command always returns true) as a browser in order to not install more dependencies.
- Let me know if you need help with the new OpenTask repo.
- Checks in PHP 8.1 are not passing, but this is not related with OpenTask

**Comment by siad007** [comment]
@jawira great stuff - will check ASAP

**Comment by mrook** [comment]
LGTM!

**Pull request merged**
